### ISSUE TITLE
Action failing due to rateLimit:null

### ISSUE THREAD

**Issue by RrezeartaThaqiRB** [nicklegan/github-org-repo-metrics-action#25]
### Describe the bug

Action fails with the error "Error: Cannot read property 'remaining' of null". We don't have the rate limiting configured in our GitHub Enterprise Server and it shows rateLimit: null and as a result the action cannot read the 'remaining' property of rateLimit.

### To Reproduce

This happens when executing our workflow that uses this action.

### Expected behavior

The case when rateLimit is null to be handled so the action won't fail.

### Additional context

-

**Comment by Rrezeartaa** [comment]
@nicklegan

**Comment by nicklegan** [comment]
@Rrezeartaa try again with latest update
